/* Shared data and helpers for the frontend-only MedSupply demo. */
const seedInventory = [
    { id: 'MED001', name: 'Paracetamol 500mg', category: 'Medicine', supplier: 'ABC Pharma', quantity: 450, reorder: 100, price: 2.5, expiry: '2027-04-15', updated: 'Today, 09:42 AM' },
    { id: 'MED002', name: 'Insulin', category: 'Medicine', supplier: 'HealthCare Ltd', quantity: 45, reorder: 50, price: 350, expiry: '2026-11-20', updated: 'Today, 08:20 AM' },
    { id: 'MED003', name: 'Amoxicillin 250mg', category: 'Medicine', supplier: 'ABC Pharma', quantity: 72, reorder: 80, price: 18, expiry: '2026-10-04', updated: 'Yesterday, 04:15 PM' },
    { id: 'SUP001', name: 'Surgical Gloves', category: 'PPE', supplier: 'MediSupply', quantity: 80, reorder: 100, price: 12, expiry: '2028-02-10', updated: 'Today, 07:55 AM' },
    { id: 'SUP002', name: 'Face Masks', category: 'PPE', supplier: 'SafeMed', quantity: 1200, reorder: 300, price: 5, expiry: '2029-01-15', updated: 'Yesterday, 11:30 AM' },
    { id: 'SUP003', name: 'IV Cannula 22G', category: 'Surgical Supplies', supplier: 'CarePoint', quantity: 310, reorder: 150, price: 24, expiry: '2027-08-21', updated: 'Sep 13, 02:10 PM' },
    { id: 'EQ001', name: 'Digital Thermometer', category: 'Equipment', supplier: 'MedEquip', quantity: 15, reorder: 20, price: 450, expiry: '2030-05-12', updated: 'Sep 12, 01:24 PM' },
    { id: 'EQ002', name: 'Pulse Oximeter', category: 'Equipment', supplier: 'MedEquip', quantity: 0, reorder: 10, price: 1250, expiry: '2029-06-18', updated: 'Sep 11, 10:42 AM' },
    { id: 'LAB001', name: 'Blood Collection Tubes', category: 'Laboratory Supplies', supplier: 'LabSource', quantity: 520, reorder: 200, price: 8, expiry: '2026-09-30', updated: 'Today, 06:35 AM' },
    { id: 'MED004', name: 'Ceftriaxone 1g', category: 'Medicine', supplier: 'HealthCare Ltd', quantity: 120, reorder: 60, price: 42, expiry: '2027-01-14', updated: 'Sep 10, 03:20 PM' }
];
const MedSupply = { categories: ['Medicine', 'PPE', 'Equipment', 'Surgical Supplies', 'Laboratory Supplies'], getInventory() { const saved = localStorage.getItem('medsupply-inventory'); if (!saved) { localStorage.setItem('medsupply-inventory', JSON.stringify(seedInventory)); return [...seedInventory]; } try { return JSON.parse(saved) } catch { return [...seedInventory] } }, saveInventory(items) { localStorage.setItem('medsupply-inventory', JSON.stringify(items)) }, status(item) { if (Number(item.quantity) === 0) return 'Out of Stock'; if (Number(item.quantity) <= Number(item.reorder)) return 'Low Stock'; return 'In Stock' }, daysUntil(date) { return Math.ceil((new Date(`${date}T23:59:59`) - new Date()) / 86400000) }, expiryStatus(item) { const days = this.daysUntil(item.expiry); return days < 0 ? 'Expired' : days <= 30 ? 'Expiring Soon' : 'Safe' }, formatCurrency(value) { return `₹${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 0 })}` }, getStats() { const items = this.getInventory(); return { items: items.length, low: items.filter(i => this.status(i) === 'Low Stock').length, expired: items.filter(i => this.expiryStatus(i) === 'Expired').length, expiring: items.filter(i => ['Expired', 'Expiring Soon'].includes(this.expiryStatus(i))).length, value: items.reduce((sum, i) => sum + i.quantity * i.price, 0), available: items.reduce((sum, i) => sum + Number(i.quantity), 0), out: items.filter(i => this.status(i) === 'Out of Stock').length } } };
window.MedSupply = MedSupply;
